---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhooks-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - bundledeployments
  verbs:
  - list
  - watch
