run:
  # Default timeout is 1m, up to give more room
  timeout: 4m

linters:
  enable:
  - asciicheck
  - bodyclose
  - errorlint
  - gofmt
  - goimports
  - gosec
  - importas
  - misspell
  - nestif
  - nonamedreturns
  - prealloc
  - revive
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  errorlint:
    errorf: false

  importas:
    alias:
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: apierrors
    - pkg: github.com/operator-framework/rukpak/api/v1alpha1
      alias: rukpakv1alpha1
  goimports:
    local-prefixes: github.com/operator-framework/rukpak

output:
  format: tab
