FROM --platform=$BUILDPLATFORM gcr.io/distroless/static:debug
LABEL stage=rukpak
WORKDIR /
# bundle unpack Jobs require cp at /bin/cp
RUN ["/busybox/ln", "-s", "/busybox/cp", "/bin/cp"]

# copy goreleaser built binaries
COPY plain plain
COPY unpack unpack
COPY core core

EXPOSE 8080
ENTRYPOINT ["/plain"]
