apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: prometheus
spec:
  provisionerClassName: core-rukpak-io-plain
  source:
    type: image
    image:
      ref: quay.io/operatorhubio/prometheus:v0.65.0
