apiVersion: v1
kind: Service
metadata:
  namespace: olmv1-system
  name: helm-provisioner
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: helm-provisioner
