---
apiVersion: v1
kind: Service
metadata:
  name: rukpak-webhook
  namespace: rukpak-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: core-webhook
