---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: rukpak-webhook
  annotations:
    cert-manager.io/inject-ca-from: rukpak-system/rukpak-webhook-certificate
webhooks:
- name: bundle-rukpak-webhook.rukpak-system.svc
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: rukpak-webhook
      namespace: rukpak-system
      path: /validate-core-rukpak-io-v1alpha1-bundle
      port: 443
  failurePolicy: Fail
  rules:
  - apiGroups:
    - core.rukpak.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bundles
  sideEffects: None
