---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: binary-manager-admin
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - core.rukpak.io
  resources:
    - bundles/status
  verbs:
    - update
    - patch
