apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rukpak-admin-role
  namespace: rukpak
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rukpak-admin-rolebinding
  namespace: rukpak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rukpak-admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: rukak-admin
