
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles/status
  verbs:
  - patch
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - provisionerclasses
  verbs:
  - create
  - delete
  - patch
  - update
