resources:
- ../../base # Include all base manifests, apply the following resources and changes over the top
- resources/apis
- resources/core
- resources/crdvalidator
- resources/provisioners

patches:
- target: 
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  path: patches/validating_webhook_cainjection.yaml
- target: 
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: crd-validation-webhook
  path: patches/crd_validation_cainjection.yaml
- target:
    kind: Deployment
    name: core
  path: patches/core_deployment_certs.yaml
# - target:
#     kind: Deployment
#     name: helm-provisioner
#   path: patches/helm_provisioner_deployment_certs.yaml

replacements:
- source: # replaces CERTIFICATE_NAMESPACE with namespace of the certificate CR
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: rukpak-webhook-certificate # this name should match the one in certificate.yaml
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    fieldPaths: 
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 0
- source: # replaces CERTIFICATE_NAME with name of the certificate CR
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: rukpak-webhook-certificate # this name should match the one in certificate.yaml
    fieldPath: metadata.name
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    fieldPaths: 
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
  - select:
      kind: Deployment
      name: webhooks
      namespace: system
    fieldPaths:
    - spec.template.spec.volumes.[name=cert].secret.secretName
- source: # replaces CERTIFICATE_NAME with name of the certificate CR
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: crd-validation-webhook-certificate # this name should match the one in certificate.yaml
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment
      name: crd-validation-webhook
      namespace: crdvalidator-system
    fieldPaths:
    - spec.template.spec.volumes.[name=tls].secret.secretName
- source: # replaces SERVICE_NAMESPACE with namespace of the service
    kind: Service
    version: v1
    name: webhook-service
    fieldPath: metadata.namespace
  targets:
  - select:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: rukpak-webhook-certificate
      namespace: system
    fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 1
- source: # replaces SERVICE_NAME with namespace of the service
    kind: Service
    version: v1
    name: webhook-service
    fieldPath: metadata.name
  targets:
  - select:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: rukpak-webhook-certificate
      namespace: system
    fieldPaths:
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 0
