resources:
- core.rukpak.io_bundledeployments.yaml
patches:
- path: patches/bundledeployment_validation.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: bundledeployments.core.rukpak.io
