apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rukpak-core-admin
  namespace: rukpak-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rukpak-core-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: rukpak-core-admin
    namespace: rukpak-system
