apiVersion: apps/v1
kind: Deployment
metadata:
  name: crd-validation-webhook
  namespace: crdvalidator-system
spec:
  selector:
    matchLabels:
      app: crd-validation-webhook
  template:
    metadata:
      labels:
        app: crd-validation-webhook
    spec:
      serviceAccountName: crd-validation-webhook
      containers:
        - image: quay.io/operator-framework/rukpak:devel
          imagePullPolicy: IfNotPresent
          command: ["/crdvalidator"]
          name: crd-validation-webhook
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
      volumes:
        - name: tls
          secret:
            secretName: crd-validation-webhook-certificate
