
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: plain-provisioner-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - core.rukpak.io
  resources:
  - bundleinstances
  verbs:
  - list
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - bundleinstances/finalizers
  verbs:
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - bundleinstances/status
  verbs:
  - patch
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles
  verbs:
  - list
  - watch
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles/finalizers
  verbs:
  - update
- apiGroups:
  - core.rukpak.io
  resources:
  - bundles/status
  verbs:
  - patch
  - update
