name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - run: make build

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        uses: docker/build-push-action@v1
        with:
          repository: operator-framework/rukpak
          dockerfile: ./Dockerfile
          push: false
