name: go-apidiff

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
    - main

jobs:
  go-apidiff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
      id: go
    - name: Run go-apidiff
      uses: joelanford/go-apidiff@main
