name: release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
    - main

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.17

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Run goreleaser
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          export GORELEASER_ARGS="--rm-dist"
        fi
        make release
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: List docker images
      if: startsWith(github.ref, 'refs/tags') == false
      run: docker images
