name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17'
      - run: make test-unit
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.17'
    - name: Install kind
      env:
        KIND_VERSION: v0.11.1
        KIND_OS: kind-linux-amd64
      run: |
        curl -sLo kind "https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/${KIND_OS}"
        chmod +x kind
        sudo mv kind /bin/
    - name: Create kind cluster
      run: |
        kind version
        kind create cluster
        kind export kubeconfig
    - name: Install the rukpak k8s provisioner
      run: |
        make generate
        kubectl create namespace rukpak-system
        kubectl apply -f manifests

        # Note: run the provisioner in the background so we don't block
        # running ginkgo tests in the foreground.
        # TODO: remove this hack when we have k8s provisioner manifests
        # and more fleshed out CI pipeline that builds/pushes the unpack
        # and provisioner image(s) so we can reference them at runtime.
        nohup go run provisioner/k8s/main.go &
    - name: Run e2e tests
      run: |
        make test-e2e
